local given, host = ...
return host.text(host.output, [[for f in repo/AGENTS.md repo/README.md; do awk -v F="$f" '/^```/{fence=!fence} !fence && /^#+ /{lvl=length($1); if(p && lvl<=plvl) p=0; if(!p && tolower($0) ~ /requirement/){p=1; plvl=lvl; print "== " F}} p' "$f"; done]])
