local given, host = ...
return host.text(host.output, [[f=$(grep -c "^.. stkh_req::" repo/docs/stakeholder/*.rst | sort -t: -k2 -n | tail -1 | cut -d: -f1); awk '/^\.\. stkh_req::/{buf=""; p=1} p{buf=buf $0 "\n"} END{printf "%s", buf}' "$f"]])
