local given, host = ...
return host.text(host.output, [[for f in repo/docs/stakeholder/*.rst; do echo "== $f: $(grep -c "^.. stkh_req::" "$f") goals"; sed -n "1,14p" "$f"; grep -A1 "^.. stkh_req::" "$f" | grep -v "^--"; done]])
